/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/users/": {
    /** @description Create a new user */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            name: string;
            password: string;
            /** @default recruiter */
            role: string;
          };
        };
      };
      responses: {
        /** @description Success */
        201: {
          content: {
            "application/json": {
              id: string;
              /** Format: email */
              email: string;
              name: string;
              role: string;
            };
          };
        };
      };
    };
  };
  "/auth/login": {
    /** @description User login (JWT) */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": {
              token: string;
            };
          };
        };
      };
    };
  };
  "/auth/logout": {
    /** @description Logout (client discards JWT) */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/candidates/stats": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/candidates/": {
    /** @description Listar candidatos recientes */
    get: {
      responses: {
        /** @description Success */
        200: {
          content: {
            "application/json": ({
                id: string;
                firstName: string;
                lastName: string;
                /** Format: email */
                email: string;
                phone?: string | null;
                resumeUrl?: string | null;
                createdAt: string;
              })[];
          };
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = {
  schemas: {
    Example: {
      id: string;
      name: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
